#module_parameters(INDEX_TYPE: Type = u32, GENERATION_TYPE: Type = u32);

#load "src/component/archetype.jai";
#load "src/component/archetype_id.jai";
#load "src/component/archetype_storage.jai";
#load "src/component/component.jai";
#load "src/component/components.jai";
#load "src/component/paged_sparse_array.jai";
#load "src/component/sparse_set.jai";
#load "src/component/sparse_set_storage.jai";

#load "src/entity/entity.jai";
#load "src/entity/entities.jai";

#load "src/query/iterate.jai";
#load "src/query/plan.jai";
#load "src/query/query.jai";
#load "src/query/row.jai";
#load "src/query/terms.jai";

#load "src/util.jai";
#load "src/world.jai";
