#load "src/component/archetype.jai";
#load "src/component/archetype_id.jai";
#load "src/component/archetype_storage.jai";
#load "src/component/component.jai";
#load "src/component/components.jai";
#load "src/component/paged_sparse_array.jai";
#load "src/component/sparse_set.jai";
#load "src/component/sparse_set_storage.jai";

#load "src/entity/entities.jai";
#load "src/entity/entity.jai";

#load "src/util.jai";
#load "src/world.jai";
